// Code generated by mockery v2.53.3. DO NOT EDIT.

package mock

import (
	context "context"
	entity "order-pick-up-point/internal/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// PvzService is an autogenerated mock type for the PvzService type
type PvzService struct {
	mock.Mock
}

// GetPVZList provides a mock function with given fields: ctx
func (_m *PvzService) GetPVZList(ctx context.Context) ([]entity.Pvz, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPVZList")
	}

	var r0 []entity.Pvz
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Pvz, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Pvz); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Pvz)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPvzService creates a new instance of PvzService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPvzService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PvzService {
	mock := &PvzService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
